stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
  after_script:
    - echo "End build"

deploy-job:      # This job runs in the deploy stage.
  stage: deploy
  script:
    - echo "Deploying application.."
    - docker build . -t eu.gcr.io/rb08-streamy/streamy-frontend:latest
    - C:\deployment-frontend.sh
  after_script:
    - echo done deploying


